services:
  postech-contacts:
    image: postech/contacts:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    build:
      context: .
      dockerfile: src/PosTech.Contacts.Api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - metrics
    container_name: postech-contacts
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    environment:
      MSSQL_SA_PASSWORD: "48GVHstRKlKW7aJxQKO4DMZziiDCrIAD"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - metrics
    container_name: sqlserver

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - metrics
    container_name: prometheus

  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - metrics
    depends_on: 
      - prometheus
    container_name: grafana

networks:
  metrics:
    driver: bridge
