global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [localhost:9090]

  - job_name: 'postech-contacts'
    scrape_interval: 5s
    static_configs:
      - targets: [postech-contacts:5080]
  
  - job_name: 'postech-contacts-search'
    scrape_interval: 5s
    static_configs:
      - targets: [postech-contacts-search:5081]
  
  - job_name: 'postech-contacts-worker'
    scrape_interval: 5s
    static_configs:
      - targets: [postech-contacts-worker:5082]
