apiVersion: v1
kind: ConfigMap
metadata: 
  name: cluster-config
  labels:
    name: cluster-config
data:
  RABBITMQ_PORT: "5672"
  RABBITMQ_HOSTNAME: svc-rabbitmq
  RABBITMQ_VIRTUALHOST: /
  RABBITMQ_USERNAME: admin
  MONGODB_DATABASE_NAME: pos-tech-contacts
  RABBITMQ_DEFAULT_USER: "admin"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  ME_CONFIG_BASICAUTH_USERNAME: "gustavofpeixoto"
  ME_CONFIG_MONGODB_PORT: "80"
  ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
  ME_CONFIG_MONGODB_SERVER: "svc-mongo"