apiVersion: v1
kind: Service
metadata:
  name: svc-contacts-api-search
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32001
  selector:
    app: contacts-api-search