apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-api-search-deployment
  labels:
    app: contacts-api-search-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: contacts-api-search
  template:
    metadata:
      labels:
        app: contacts-api-search
    spec:
      containers:
        - name: contacts-api-search
          image: gustavofpeixoto/postech:contacts-api-search
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: RABBITMQ_HOSTNAME
            - name: RABBITMQ_VIRTUALHOST
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: RABBITMQ_VIRTUALHOST
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opaque-secret
                  key: RABBITMQ_PASSWORD
            - name: MONGODB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: MONGODB_DATABASE_NAME
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: opaque-secret
                  key: MONGODB_CONNECTION_STRING