apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-api-deployment
  labels:
    app: contacts-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contacts-api
  template:
    metadata:
      labels:
        app: contacts-api
    spec:
      containers:
        - name: contacts-api
          image: gustavofpeixoto/postech:contacts-api
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: RABBITMQ_HOSTNAME
            - name: RABBITMQ_VIRTUALHOST
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: RABBITMQ_VIRTUALHOST
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opaque-secret
                  key: RABBITMQ_PASSWORD
            - name: SQLSERVER_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: opaque-secret
                  key: SQLSERVER_CONNECTION_STRING