apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  containers:
    - name: mongo-express
      image: mongo-express:latest
      ports:
        - containerPort: 8081
      env:
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: ME_CONFIG_BASICAUTH_USERNAME
        - name: ME_CONFIG_MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: ME_CONFIG_MONGODB_PORT
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: ME_CONFIG_MONGODB_ADMINUSERNAME
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: cluster-config
              key: ME_CONFIG_MONGODB_SERVER
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opaque-secret
              key: ME_CONFIG_BASICAUTH_PASSWORD
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: opaque-secret
              key: ME_CONFIG_MONGODB_ADMINPASSWORD