apiVersion: v1
kind: Secret
metadata: 
  name: opaque-secret
  labels:
    name: opaque-secret
type: Opaque
stringData:
  SQLSERVER_CONNECTION_STRING: "Server=sqlserver;Database=SqlDb-PosTech-Contacts;User ID=sa;Password=48GVHstRKlKW7aJxQKO4DMZziiDCrIAD;Trusted_Connection=False; TrustServerCertificate=True;"
  MONGODB_CONNECTION_STRING: "mongodb://admin:rHQaXMpbu02xTHkOpcyREw@mongo:27017"
  RABBITMQ_PASSWORD: "L38IwqjTXku0mxvCtKvNqw"
  MSSQL_SA_PASSWORD: "48GVHstRKlKW7aJxQKO4DMZziiDCrIAD"
  ACCEPT_EULA: "Y"
  RABBITMQ_DEFAULT_PASS: "L38IwqjTXku0mxvCtKvNqw"
  MONGO_INITDB_ROOT_PASSWORD: "rHQaXMpbu02xTHkOpcyREw"
  ME_CONFIG_BASICAUTH_PASSWORD: "local"
  ME_CONFIG_MONGODB_ADMINPASSWORD: "rHQaXMpbu02xTHkOpcyREw"