apiVersion: v1
kind: Service
metadata:
  name: svc-prometheus
  labels:
    app: svc-prometheus
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 32004
  selector:
    app: prometheus