// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosTech.Contacts.Infrastructure;

#nullable disable

namespace PosTech.Contacts.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250115235912_AddColumnStateToDdds")]
    partial class AddColumnStateToDdds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosTech.Contacts.ApplicationCore.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DddId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Surname")
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DddId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("PosTech.Contacts.ApplicationCore.Entities.Ddd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DddCode")
                        .HasColumnType("int");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Ddds");
                });

            modelBuilder.Entity("PosTech.Contacts.ApplicationCore.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegionName")
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("PosTech.Contacts.ApplicationCore.Entities.Contact", b =>
                {
                    b.HasOne("PosTech.Contacts.ApplicationCore.Entities.Ddd", "Ddd")
                        .WithMany("Contacts")
                        .HasForeignKey("DddId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ddd");
                });

            modelBuilder.Entity("PosTech.Contacts.ApplicationCore.Entities.Ddd", b =>
                {
                    b.HasOne("PosTech.Contacts.ApplicationCore.Entities.Region", "Region")
                        .WithMany("Ddds")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PosTech.Contacts.ApplicationCore.Entities.Ddd", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("PosTech.Contacts.ApplicationCore.Entities.Region", b =>
                {
                    b.Navigation("Ddds");
                });
#pragma warning restore 612, 618
        }
    }
}
