name: Workflow build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore PosTech.Contacts.sln

      - name: Build all projects
        run: dotnet build --configuration Debug

  unit_tests:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build unit tests projects
        run: dotnet build --configuration Debug

      - name: Run unit tests
        run: |
          dotnet test tests\PosTech.Contacts.UnitTests\PosTech.Contacts.UnitTests.csproj --configuration Debug --no-build --verbosity normal

  integration_tests:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build integration tests projects
        run: dotnet build --configuration Debug

      - name: Run integration tests
        run: |
          dotnet test tests\PosTech.Contacts.IntegrationTests\PosTech.Contacts.IntegrationTests.csproj --configuration Debug --no-build --verbosity normal